name: clippy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check Rust version
      run: rustc -V
    - name: Install lld linker for faster build times
      run: sudo apt -y install lld
    - name: a
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy --workspace --all-targets -- -D warnings  # treat warnings as errors